-- H2 Schema for Testing
DROP TABLE IF EXISTS room_service;
DROP TABLE IF EXISTS room_image;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS motel;

-- Tabla de moteles
CREATE TABLE motel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    description VARCHAR(500),
    city VARCHAR(100) NOT NULL,
    property_id BIGINT,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para motel
CREATE INDEX idx_motel_city ON motel(city);
CREATE INDEX idx_motel_property ON motel(property_id);

-- Tabla de habitaciones
CREATE TABLE room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motel_id BIGINT NOT NULL,
    number VARCHAR(20) NOT NULL,
    room_type VARCHAR(50) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    description VARCHAR(500),
    is_available BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (motel_id) REFERENCES motel(id) ON DELETE CASCADE,
    UNIQUE (motel_id, number)
);

-- Índices para room
CREATE INDEX idx_room_motel ON room(motel_id);
CREATE INDEX idx_room_available ON room(is_available);

-- Tabla de imágenes de habitaciones
CREATE TABLE room_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (room_id) REFERENCES room(id) ON DELETE CASCADE
);

-- Índices para room_image
CREATE INDEX idx_room_image_room ON room_image(room_id);
CREATE INDEX idx_room_image_order ON room_image(room_id, display_order);

-- Tabla de servicios
CREATE TABLE service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    icon VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índice para service
CREATE INDEX idx_service_name ON service(name);

-- Tabla intermedia para la relación muchos-a-muchos entre room y service
CREATE TABLE room_service (
    room_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    PRIMARY KEY (room_id, service_id),
    FOREIGN KEY (room_id) REFERENCES room(id) ON DELETE CASCADE,
    FOREIGN KEY (service_id) REFERENCES service(id) ON DELETE CASCADE
);

-- Índices para room_service
CREATE INDEX idx_room_service_room ON room_service(room_id);
CREATE INDEX idx_room_service_service ON room_service(service_id);
